### ISSUE TITLE
Doesn't compile with ESP-IDF v5.1 ; which version was originally used, please?

### ISSUE THREAD

**Issue by crosswick** [Jeija/esp32-lyrat-passthrough#1]
Thanks by the way, this looks very useful.

**Comment by Jeija** [comment]
I don't know, probably the ESP-IDF version that was most recent 5 years ago... Unfortunately, I can't test this since I don't have access to the LyraT board anymore. But kindly let me know / send a PR if you get this working with the latest ESP-IDF.

**Comment by crosswick** [comment]
I see, I'll look into it, thanks for the quick reply.

**Comment by crosswick** [comment]
Seems that the current version at the time of your initial upload (2 January 2020, so actually a little over 4 years ago) was https://github.com/espressif/esp-idf/releases/tag/v3.3.1 - unfortunately there's no migration guide available for this. 

In stead of migrating, I think this current i2s example might be a good starting point: https://github.com/espressif/esp-idf/tree/release/v5.1/examples/peripherals/i2s/i2s_codec/i2s_es8311
